# Generated by Django 4.2.2 on 2023-07-10 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0002_order_profile_orderentry_order_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderentry',
            name='product',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderEntry',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
