# Generated by Django 4.2.2 on 2023-07-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0006_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='massa',
            field=models.FloatField(default=100.0),
        ),
    ]
