# Generated by Django 4.2.2 on 2023-07-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0011_answer_profile_answerentry_answer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerentry',
            name='weight_of_the_product',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='kcal',
            field=models.IntegerField(default=0),
        ),
    ]
