# Generated by Django 4.2.2 on 2023-07-14 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0013_alter_answerentry_weight_of_the_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerentry',
            name='weight_of_the_product',
        ),
    ]
