# Generated by Django 4.2.2 on 2023-07-31 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0016_rename_count_answerentry_mass_of_the_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massa', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='answerentry',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answerentry',
            name='product',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_ration',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='AnswerEntry',
        ),
        migrations.AddField(
            model_name='note',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='diet_diary.profile'),
        ),
        migrations.AddField(
            model_name='getnote',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_notes', to='diet_diary.note'),
        ),
        migrations.AddField(
            model_name='getnote',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='diet_diary.product'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='diet_diary.note'),
        ),
    ]
