# Generated by Django 4.2.2 on 2023-07-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0017_getnote_note_remove_answerentry_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getnote',
            name='massa',
            field=models.FloatField(default=100.0),
        ),
    ]
