# Generated by Django 4.2.2 on 2023-07-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0018_alter_getnote_massa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getnote',
            name='massa',
            field=models.FloatField(default=0.0),
        ),
    ]
