# Generated by Django 4.2.2 on 2023-07-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0020_remove_getnote_massa'),
    ]

    operations = [
        migrations.AddField(
            model_name='getnote',
            name='massa',
            field=models.FloatField(default=0.0),
        ),
    ]
