# Generated by Django 4.2.2 on 2023-08-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0021_getnote_massa'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=12.57),
            preserve_default=False,
        ),
    ]
