# Generated by Django 4.2.2 on 2023-08-02 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0022_note_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
    ]
