# Generated by Django 4.2.2 on 2023-08-02 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0026_timestampmixin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeStampMixin',
        ),
        migrations.AddField(
            model_name='getnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
