# Generated by Django 4.2.2 on 2023-08-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0032_time_remove_getnote_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
