# Generated by Django 4.2.2 on 2023-08-03 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_diary', '0033_alter_time_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
    ]
